//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticari_Otomasyon_Proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIller
    {
        public int Id { get; set; }
        public string Sehir { get; set; }
    }
}
